'use client';
import { useState } from 'react';
import { ArrowUpRight, Check, Copy } from 'lucide-react';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
export function ContactForm(){
 const [teamSize,setTeamSize]=useState('');const [draft,setDraft]=useState('');const [mailLink,setMailLink]=useState('');const [copied,setCopied]=useState(false);
 function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);const text=`Hi Elevix,\n\n${data.get('message')}\n\nName: ${data.get('name')}\nEmail: ${data.get('email')}\nPhone: ${data.get('phone')||'Not provided'}\nCompany: ${data.get('company')||'Not provided'}\nCompany size: ${teamSize||'Not provided'}`;const link='mailto:sales@elevixtech.com?subject='+encodeURIComponent('Let’s build together — '+data.get('name'))+'&body='+encodeURIComponent(text);setDraft(text);setMailLink(link);setCopied(false);window.location.href=link;}
 async function copy(){try{await navigator.clipboard.writeText(draft);setCopied(true);}catch{setCopied(false);}}
 return <form className="contact-form" onSubmit={submit}><h2>Tell us what you have in mind.</h2><p className="form-note">We’ll prepare an email for you to review and send from your email app.</p><div className="form-row"><div className="field"><label htmlFor="name">Full name *</label><input id="name" name="name" placeholder="Your name" required maxLength={100} autoComplete="name"/></div><div className="field"><label htmlFor="email">Work email *</label><input id="email" type="email" name="email" placeholder="you@company.com" required maxLength={200} autoComplete="email"/></div></div><div className="form-row"><div className="field"><label htmlFor="company">Company name</label><input id="company" name="company" placeholder="Your company" maxLength={150} autoComplete="organization"/></div><div className="field"><label htmlFor="phone">Phone number</label><input id="phone" type="tel" name="phone" placeholder="Your phone number" maxLength={40} autoComplete="tel"/></div></div><div className="field"><label htmlFor="team-size">Company size</label><Select value={teamSize} onValueChange={setTeamSize}><SelectTrigger id="team-size" className="w-full min-h-12 bg-[#f9fcfa]"><SelectValue placeholder="Select company size"/></SelectTrigger><SelectContent>{['1–25','26–50','51–250','251–1,000','1,001–5,000','5,000+'].map(s=><SelectItem key={s} value={s}>{s} people</SelectItem>)}</SelectContent></Select></div><div className="field"><label htmlFor="message">How can we help? *</label><textarea id="message" name="message" required minLength={10} maxLength={1500} placeholder="A little about your project, goals, or the challenge you’re solving…" rows={5}/></div><button type="submit" className="button button-dark">Prepare my email <ArrowUpRight size={18}/></button>{draft&&<div className="form-result" role="status"><strong>Your email draft is ready.</strong><p>Send it from your email app to complete your enquiry. If your app didn’t open, <a href={mailLink}>open the draft again</a> or copy the message and email sales@elevixtech.com.</p><div className="email-copy"><span>No message has been sent by this website.</span><button type="button" onClick={copy}>{copied?<><Check size={14}/> Copied</>:<><Copy size={14}/> Copy message</>}</button></div></div>}</form>
}
