import Link from 'next/link';
import { ArrowUpRight, ArrowRight } from 'lucide-react';
import { services, caseStudies } from '@/lib/content';
import type { Post } from '@/lib/wordpress';
import { FlipServices } from './experience';
import { AnimatedText } from './motion-system';
export function ServiceGrid(){return <FlipServices/>}
const caseImages=['/images/ai-glass.webp','/images/product-glass.webp','/images/service-cloud.webp'];
export function CaseGrid({limit=3}:{limit?:number}){return <div className="case-grid">{caseStudies.slice(0,limit).map((c,i)=><Link className="case-card" href={'/case-studies/'+c.slug} key={c.slug} data-cursor="view"><div className={'case-visual case-with-image '+c.color}><img src={caseImages[i]} alt="" loading="lazy"/><span className="case-label">{c.label}</span><div className="case-visual-bottom"><span>{c.tools[0]}</span><span className="round-arrow"><ArrowUpRight size={20}/></span></div></div><div className="case-copy"><h3>{c.title}</h3><p>{c.description}</p></div></Link>)}</div>}
export function PostGrid({posts}:{posts:Post[]}){return <div className="post-grid">{posts.map((p,i)=><article className="post-card" key={p.slug}><Link href={'/blogs/'+p.slug} data-cursor="view" className={'post-visual post-color-'+i%3}>{p.image?<img src={p.image} alt="" loading="lazy"/>:<img src="/images/ai-glass.webp" alt="" loading="lazy"/>}<span className="post-image-tag">{p.category}</span><span className="post-image-arrow"><ArrowUpRight size={20}/></span></Link><div className="post-meta">{p.category}<span>·</span>{new Date(p.date).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'})}</div><Link href={'/blogs/'+p.slug}><h3>{p.title}</h3></Link><Link href={'/blogs/'+p.slug} className="text-link">Read article <ArrowRight size={16}/></Link></article>)}</div>}
export function PageIntro({eyebrow,title,description,image}:{eyebrow:string,title:string,description:string,image?:string}){const idx=services.findIndex(s=>s.title===eyebrow);const serviceImage=services[idx]?.image;const selected=image??(idx>=0?serviceImage:eyebrow==='Overview'||eyebrow==='Careers'?'/images/workspace.webp':eyebrow==='Blog'?'/images/ai-glass.webp':eyebrow==='FAQ'?'/glass-hero.webp':'/images/product-glass.webp');return <section className="page-intro container"><div className="breadcrumb"><Link href="/">Home</Link><span>/</span>{eyebrow}</div><div className="page-intro-grid"><div className="page-intro-copy"><span className="eyebrow"><span className="status-dot"/>{eyebrow}</span><h1><AnimatedText text={title}/></h1><p>{description}</p><span className="page-intro-line"/></div><div className="page-intro-visual" data-parallax><img data-parallax-image src={selected} alt={eyebrow==='Careers'||eyebrow==='Overview'?'Conceptual collaborative studio':'Digital technology concept artwork'} width="700" height="600"/><span className="page-visual-index">E / {eyebrow.toUpperCase()}</span><span className="page-visual-arrow"><ArrowUpRight size={30}/></span></div></div></section>}
