'use client';
import Link from 'next/link';
import { ServiceIcon } from './service-icon';
import { ArrowRight, ArrowUpRight, CheckCircle2, Layers3 } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { serviceDetails, type ServiceDetail } from '@/lib/service-details';

const examples:Record<string,{title:string;context:string;steps:string[];result:string;image:string;alt:string}>={
 workplace:{title:'An approval that keeps moving.',context:'Illustrative workflow · internal purchase request',steps:['Employee submits a Power Apps form','Power Automate routes it to the right approver','The decision is recorded in SharePoint','Teams delivers the status to the requester'],result:'A visible decision trail, with fewer status-chasing emails.',image:'/images/m365-workplace.webp',alt:'Glass document and collaboration panels'},
 intelligence:{title:'Find the answer. See the context.',context:'Illustrative workflow · enterprise knowledge search',steps:['A colleague asks a policy question','Retrieval finds permitted source documents','The assistant drafts an answer with references','A person checks the sources before acting'],result:'Knowledge assistance grounded in approved information.',image:'/images/ml-intelligence.webp',alt:'Connected data streams around a glass intelligence core'},
 product:{title:'A customer journey, end to end.',context:'Illustrative workflow · customer self-service',steps:['A customer signs in on web or mobile','They complete a clear, accessible request form','An API validates and records the request','Status and next steps appear in their account'],result:'One coherent experience across interfaces and services.',image:'/images/glass-product.webp',alt:'Translucent phone and web product modules'},
 nextgen:{title:'From a suggestion to a safe action.',context:'Illustrative workflow · assisted service operations',steps:['An application receives a service request','An assistant proposes a contextual next step','A team member reviews and approves the action','A scoped integration executes and logs the result'],result:'Useful automation with a clear point of human control.',image:'/images/ai-glass.webp',alt:'Modular glass system for an intelligent application'},
 cloud:{title:'A release with a way back.',context:'Illustrative workflow · controlled cloud delivery',steps:['A code change passes automated checks','A pipeline creates a consistent deployment','Health checks confirm the workload is responding','Alerts and rollback support the operations team'],result:'Repeatable releases with operational visibility.',image:'/images/cloud-infrastructure.webp',alt:'Cloud infrastructure represented by connected glass server layers'}
};

export function ConnectedCapabilities(){return <section className="section glass-capabilities"><div className="container"><div className="section-heading" data-reveal><div><span className="eyebrow">FIVE SPECIALISMS. CONNECTED THINKING.</span><h2>See how the pieces<br/><span className="muted-title">work together.</span></h2></div><p className="section-note">Explore the role each capability plays, from your team's daily tools to the foundations behind your next product.</p></div><Tabs defaultValue={serviceDetails[0].slug} className="capability-explorer"><TabsList className="capability-switcher" aria-label="Explore Elevix capabilities">{serviceDetails.map((s,i)=><TabsTrigger value={s.slug} key={s.slug}><ServiceIcon slug={s.slug}/>{s.short}</TabsTrigger>)}</TabsList>{serviceDetails.map(s=><TabsContent value={s.slug} key={s.slug} className="capability-view"><div className="capability-photo"><img src={s.image} alt={s.title+' concept artwork'} loading="lazy" width="900" height="650"/><div className="capability-photo-label"><ServiceIcon slug={s.slug}/><span>{s.title}</span></div></div><div className="capability-map"><span className="eyebrow">{s.kicker}</span><h3>{s.title}</h3><p>{s.intro}</p><ol>{s.nodes.slice(0,4).map((n,i)=><li key={n.title}><span className="capability-step">0{i+1}</span><div><strong>{n.title}</strong><span>{n.text}</span></div></li>)}</ol><Link className="text-link" href={'/'+s.slug}>Explore {s.short}<ArrowUpRight size={18}/></Link></div></TabsContent>)}</Tabs></div></section>}

export function GlassFlowFeature(){return <section className="container glass-flow-feature" data-reveal><div className="glass-flow-photo" data-parallax><img data-parallax-image src="/images/glass-flow.webp" alt="A clear glass ribbon connecting five translucent architectural portals" loading="lazy" width="1200" height="800"/></div><div className="glass-flow-copy"><span className="eyebrow">FROM YOUR TEAM TO YOUR CUSTOMERS</span><h2>Connected technology.<br/>A clearer way forward.</h2><p>Workplace tools, intelligent applications and cloud infrastructure should support the same business direction.</p><div className="flow-pill-row"><span>People</span><ArrowRight size={17}/><span>Applications</span><ArrowRight size={17}/><span>Infrastructure</span></div></div></section>}

export function AppliedServiceStory({service:s}:{service:ServiceDetail}){const e=examples[s.theme];return <section className={'container applied-service applied-'+s.theme}><div className="applied-heading" data-reveal><span className="eyebrow">{s.short.toUpperCase()} IN PRACTICE</span><h2>{e.title}</h2><p>{e.context}</p></div><div className="applied-layout"><div className="applied-image" data-reveal data-parallax><img data-parallax-image src={e.image} alt={e.alt} loading="lazy" width="1000" height="800"/><span className="applied-image-label">A POSSIBLE SOLUTION PATTERN</span></div><div className="applied-workflow" data-reveal><ol>{e.steps.map((step,i)=><li key={step}><span className="workflow-marker">{i+1}</span><p>{step}</p></li>)}</ol><div className="workflow-result"><CheckCircle2 size={25}/><p>{e.result}</p></div></div></div></section>}
