import Link from 'next/link';
import { AppliedServiceStory } from './glass-stories';
import { ArrowUpRight, Check, LockKeyhole } from 'lucide-react';
import type { ServiceDetail } from '@/lib/service-details';
import { AnimatedText } from './motion-system';
import { ServiceInfographic, ServiceScenarios } from './service-infographic';
function Hero({s}:{s:ServiceDetail}){return <header className="service-hero container"><div className="breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/services">Services</Link><span>/</span>{s.title}</div><div className="service-hero-layout"><div className="service-hero-copy"><span className="eyebrow">{s.kicker}</span><h1>{s.outcome}</h1><p>{s.intro}</p><Link className="button button-dark" href={'/contact-us?service='+encodeURIComponent(s.title)}>Discuss {s.short} <ArrowUpRight size={18}/></Link></div><div className="service-hero-art" data-parallax><img data-parallax-image src={s.image} alt={s.title+' conceptual illustration'} width="1200" height="800"/><span className="art-caption">ELEVIX / {s.short.toUpperCase()}</span></div></div></header>}
function Scope({s}:{s:ServiceDetail}){return <section className="container service-scope"><span className="eyebrow">{s.title.toUpperCase()} / EXPERTISE</span><div className="scope-grid">{s.capabilities.map((c,i)=><article key={c}><span>0{i+1}</span><h3>{c}</h3></article>)}</div></section>}
function Editorial({s}:{s:ServiceDetail}){return <section className="container service-editorial">{s.sections.map((c,i)=><article key={c.title} data-reveal><span className="editorial-number">0{i+1}</span><div><h2>{c.title}</h2><p>{c.text}</p></div></article>)}</section>}
function Handover({s}:{s:ServiceDetail}){return <section className="container service-handover" data-reveal><div><span className="eyebrow">CLEAR SCOPE. USEFUL OUTPUTS.</span><h2>What we can deliver.</h2><p>The final scope is agreed around your systems, priorities and constraints.</p></div><ul>{s.deliverables.map(d=><li key={d}><Check size={18}/>{d}</li>)}</ul></section>}
function Questions({s}:{s:ServiceDetail}){return <section className="container service-questions"><span className="eyebrow">BEFORE WE BEGIN</span><h2>Your {s.short} questions.</h2>{s.faq.map(f=><details key={f.q}><summary>{f.q}<span>+</span></summary><p>{f.a}</p></details>)}</section>}
function Closing({s}:{s:ServiceDetail}){const copy:Record<string,[string,string]>={workplace:['Make your workplace work better.','Start with the process your team wants to simplify.'],intelligence:['Find your first useful AI opportunity.','Bring a business challenge. We’ll help frame a testable starting point.'],product:['What should your next product make possible?','Let’s talk users, platforms and the first release.'],nextgen:['Design the next intelligent interaction.','Choose a real workflow. Define what good looks like.'],cloud:['Give your next stage a stronger foundation.','Tell us about your workloads, constraints and migration goals.']};return <section className="container service-closing" data-reveal><span className="eyebrow">LET’S TALK / {s.short.toUpperCase()}</span><h2>{copy[s.theme][0]}</h2><p>{copy[s.theme][1]}</p><Link href={'/contact-us?service='+encodeURIComponent(s.title)} className="button button-dark">Start a conversation <ArrowUpRight size={18}/></Link></section>}
export function UniqueServicePage({service:s}:{service:ServiceDetail}){return <main id="main" className={'inner-main unique-service service-'+s.theme}><div id="top"/><Hero s={s}/>
 {s.theme==='workplace'&&<><Scope s={s}/><section className="container diagram-section"><ServiceInfographic service={s}/></section><Editorial s={s}/><div className="container service-wide-image"><img src="/images/workspace.webp" alt="Conceptual collaborative workspace" loading="lazy"/><span>People first. Connected by Microsoft 365.</span></div></>}
 {s.theme==='intelligence'&&<><section className="intelligence-lab"><div className="container"><span className="eyebrow">FROM EXPERIMENT TO EVERYDAY USE</span><ServiceInfographic service={s}/></div></section><Scope s={s}/><section className="container service-section"><h2>Choose the problem. Then the model.</h2><ServiceScenarios service={s}/></section><aside className="container guardrail-note"><LockKeyhole size={25}/><p>AI outputs need evaluation. Privacy, access controls and appropriate human review belong in the architecture—not at the end.</p></aside></>}
 {s.theme==='product'&&<><section className="container product-story"><div><span className="eyebrow">THE EXPERIENCE COMES FIRST</span><h2>One task.<br/>Every screen.<br/><em>No loose ends.</em></h2><p>Prototype the complete journey, from a first visit to a successful outcome. Then engineer the systems that make it dependable.</p></div><img src="/images/service-app.webp" alt="Web and mobile application concept" loading="lazy"/></section><section className="container diagram-section"><ServiceInfographic service={s}/></section><Editorial s={s}/><Scope s={s}/></>}
 {s.theme==='nextgen'&&<><section className="container nextgen-manifesto" data-reveal><span className="eyebrow">THE DIFFERENCE IS IN THE WORKFLOW</span><h2>Don’t just add a chat box.<br/><em>Design what happens next.</em></h2></section><section className="container nextgen-system"><ServiceInfographic service={s}/><aside><LockKeyhole size={36}/><h3>Trust is part of the product.</h3><p>Make permissions visible. Explain what the application proposes. Give users control before consequential actions.</p><img src="/images/ai-glass.webp" alt="Connected intelligent application concept" loading="lazy"/></aside></section><section className="container service-section"><ServiceScenarios service={s}/></section><Scope s={s}/></>}
 {s.theme==='cloud'&&<><section className="container cloud-blueprint"><div><span className="eyebrow">ARCHITECTURE WITH INTENT</span><h2>Resilience is<br/>a system property.</h2><p>Connect the layers with clear ownership. Security, monitoring and cost management apply across the entire foundation.</p><div className="cloud-crosscut">Security<span>Observability</span>Cost visibility</div></div><ServiceInfographic service={s}/></section><Scope s={s}/><Editorial s={s}/><div className="container service-wide-image"><img src="/images/glass-architecture.webp" alt="Layered glass architecture representing a scalable foundation" loading="lazy"/><span>Plan the move. Operate with confidence.</span></div></>}
 <AppliedServiceStory service={s}/><Handover s={s}/><Questions s={s}/><Closing s={s}/></main>}
