'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { ArrowUpRight, ChevronDown, Menu, ArrowRight } from 'lucide-react';
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from '@/components/ui/dropdown-menu';
import { services } from '@/lib/content';
import { ServiceIcon } from './service-icon';
import { AnimatedText } from './motion-system';
const company = [['Overview','/overview'],['Leadership','/leadership'],['Careers','/careers'],['FAQ','/faq']];
export function SiteHeader(){
 const path = usePathname();
 return <header className="site-header"><div className="nav-shell"><Link className="brand" href="/" aria-label="Elevix home"><img src="/elevix-logo.png" width="181" height="58" alt="Elevix" /></Link><nav className="desktop-nav" aria-label="Main navigation"><DropdownMenu><DropdownMenuTrigger className={'nav-link '+(services.some(s=>path.includes(s.slug))?'active':'')}>Our Services <ChevronDown size={14}/></DropdownMenuTrigger><DropdownMenuContent align="start" sideOffset={20} className="nav-dropdown service-megamenu"><div className="nav-editorial-image" aria-hidden="true"><img src="/images/glass-architecture.webp" alt=""/><span>CONNECTED THINKING.<br/>GREATER POSSIBILITIES.</span></div>{services.map(s=><DropdownMenuItem key={s.slug} asChild><Link href={'/'+s.slug}><ServiceIcon slug={s.slug}/><span>{s.title}</span><ArrowUpRight size={15}/></Link></DropdownMenuItem>)}<DropdownMenuItem asChild><Link href="/services">Explore all services <ArrowRight size={15}/></Link></DropdownMenuItem></DropdownMenuContent></DropdownMenu><DropdownMenu><DropdownMenuTrigger className={'nav-link '+(company.some(c=>c[1]===path)?'active':'')}>Company <ChevronDown size={14}/></DropdownMenuTrigger><DropdownMenuContent sideOffset={20} className="nav-dropdown">{company.map(([name,url])=><DropdownMenuItem key={url} asChild><Link href={url}>{name}<ArrowUpRight size={15}/></Link></DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu><Link className={'nav-link '+(path.includes('case-stud')?'active':'')} href="/case-studies">Case Studies</Link><Link className={'nav-link '+(path.includes('blog')?'active':'')} href="/blogs">Blog</Link></nav><Link className="button button-dark nav-cta" href="/contact-us">Let’s Talk <ArrowUpRight size={17}/></Link><div className="mobile-nav"><DropdownMenu><DropdownMenuTrigger className="menu-button" aria-label="Open navigation"><Menu size={24}/></DropdownMenuTrigger><DropdownMenuContent align="end" sideOffset={18} className="nav-dropdown">{[['Home','/'],['Our Services','/services'],['Company','/overview'],['Leadership','/leadership'],['Case Studies','/case-studies'],['Blog','/blogs'],['Careers','/careers'],['FAQ','/faq'],['Let’s Talk','/contact-us']].map(([name,url])=><DropdownMenuItem key={url} asChild><Link href={url}>{name}<ArrowUpRight size={15}/></Link></DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu></div></div></header>
}
export function SiteFooter(){return <footer className="site-footer"><div className="container footer-brand-stage" data-reveal><span>YOUR NEXT CHAPTER STARTS WITH</span><img src="/elevix-wordmark.svg" alt="Elevix" width="70" height="22"/><Link href="/contact-us" aria-label="Start your next chapter with Elevix"><ArrowUpRight size={48}/></Link></div><div className="container footer-top"><div className="footer-brand"><Link href="/" aria-label="Elevix home"><img src="/elevix-logo.png" width="140" height="45" alt="Elevix" /></Link><p>Good ideas deserve<br/>a great technology partner.</p><a href="mailto:sales@elevixtech.com" className="text-link">sales@elevixtech.com <ArrowUpRight size={17}/></a></div><div><h3>Our Services</h3>{services.map(s=><Link key={s.slug} href={'/'+s.slug}>{s.title}</Link>)}</div><div><h3>Company</h3><Link href="/overview">Overview</Link><Link href="/leadership">Leadership</Link><Link href="/case-studies">Case Studies</Link><Link href="/careers">Careers</Link><Link href="/faq">FAQ</Link><Link href="/blogs">Blog</Link></div><div className="footer-address"><h3>Let’s connect</h3><p>201–6660 Kennedy Road<br/>Mississauga, Ontario<br/>L5T 2M9, Canada</p><Link className="text-link" href="/contact-us">Start a conversation <ArrowUpRight size={17}/></Link></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Elevix. All rights reserved.</span><span>Ideas into impact. Together.</span><a href="#top" aria-label="Back to top">Back to top ↑</a></div></footer>}
export function CallToAction(){return <section className="container cta-wrap"><div className="cta-panel"><div><span className="eyebrow"><span className="status-dot"/>LET’S BUILD SOMETHING THAT MATTERS</span><h2><AnimatedText text="Got a bold vision?"/><br/><AnimatedText text="Let’s bring it to life."/></h2><p>Your next chapter starts with a conversation.</p></div><Link href="/contact-us" className="button button-dark">Talk to our experts <ArrowUpRight size={19}/></Link><img className="cta-glass-image" src="/images/product-glass.webp" alt="" loading="lazy"/><span className="cta-watermark" aria-hidden="true">↗</span></div></section>}
