export const dynamic='force-dynamic';
import Link from 'next/link';
import { ConnectedCapabilities, GlassFlowFeature } from './components/glass-stories';
import { ArrowUpRight, ArrowRight, Sparkles, Layers3, ShieldCheck, CodeXml, Check, Zap } from 'lucide-react';
import { HeroExperience, TechMarquee, FlipServices, OutcomeCarousel, ProcessExperience, BigMarquee, IndustryCards, HomeFaq, CountUp, VisualRibbon } from './components/experience';
import { AnimatedText } from './components/motion-system';
import { ScrollStatement, CinematicFeature, PossibilityPanels, PartnershipCards, InsightsCarousel } from './components/editorial-experience';
import { CallToAction } from './components/site-shell';
import { getPosts } from '@/lib/wordpress';
export default async function Home(){const {posts}=await getPosts();return <main id="main" className="home-expanded"><div id="top"/><HeroExperience/><TechMarquee/>
<section id="possibilities" className="section manifesto-section"><div className="container"><div className="manifesto-grid" data-reveal><span className="eyebrow"><span className="status-dot"/>THE ELEVIX WAY</span><div><h2><AnimatedText text="Big thinking. Real possibilities."/><br/><span className="muted-title"><AnimatedText text="A partner for what comes next."/></span></h2><p>We connect strategy, design, and engineering to turn your biggest challenges into your next opportunity. One collaborative team, from the first conversation to the next chapter.</p><Link href="/overview" className="text-link">Meet your technology partner <ArrowUpRight size={18}/></Link></div></div><div className="stats-band" data-reveal><CountUp value={15} suffix="+" label="Years of digital innovation"/><CountUp value={20} suffix="+" label="Talented professionals"/><CountUp value={2} label="Continents connected"/><div className="stat-promise"><span className="stat-promise-icon"><Sparkles size={25}/></span><strong>Your ambition.<br/>Our shared purpose.</strong></div></div></div></section>
<ScrollStatement/><CinematicFeature/><ConnectedCapabilities/>
<section id="services" className="section services-v2"><div className="container"><div className="section-heading"><div><span className="eyebrow"><span className="status-dot"/>CONNECTED CAPABILITIES</span><h2><AnimatedText text="The expertise to"/><br/><span className="muted-title"><AnimatedText text="take you further."/></span></h2></div><div className="heading-side"><p>From the tools your team uses every day<br/>to the products your customers love.</p><Link href="/services" className="text-link">Explore all services <ArrowUpRight size={18}/></Link></div></div><FlipServices/></div></section>
<section className="section intelligence-section"><div className="container intelligence-grid"><div className="intelligence-art image-reveal"><img src="/images/ai-glass.webp" alt="Connected translucent glass modules around an emerald intelligence core" loading="lazy"/><div className="intelligence-badge"><span className="status-dot"/>CONNECTED. INTELLIGENT. READY.</div><div className="intelligence-mini-card"><Sparkles size={23}/><span>Human ambition.<br/><strong>Intelligent possibilities.</strong></span></div></div><div className="intelligence-copy" data-reveal><span className="eyebrow">AI WITH PURPOSE</span><h2><AnimatedText text="Intelligence that"/><br/><span><AnimatedText text="works for you."/></span></h2><p>Move from exploring AI to putting it to work. Connect your people, processes, and data with intelligent solutions built around real business needs.</p><ul>{['Automate repetitive work','Connect knowledge across your business','Build intelligent customer experiences'].map(t=><li key={t}><Check size={18}/>{t}</li>)}</ul><Link href="/ai-ml-services" className="button button-light">Explore AI & ML <ArrowUpRight size={18}/></Link></div></div></section>
<section className="section why-section"><div className="container"><div className="section-heading"><div><span className="eyebrow"><span className="status-dot"/>WHY ELEVIX</span><h2><AnimatedText text="More than a service provider."/><br/><span className="muted-title"><AnimatedText text="Part of your team."/></span></h2></div><Link href="/overview" className="text-link">Get to know us <ArrowUpRight size={18}/></Link></div><div className="why-grid">{[{n:'01',icon:Sparkles,title:'Innovation with intention',text:'Start with the right problem. Find the right technology. Make something that matters.'},{n:'02',icon:Layers3,title:'Connected from day one',text:'Designers, engineers, and your team working together with clear communication and shared goals.'},{n:'03',icon:ShieldCheck,title:'A foundation for the future',text:'Thoughtful architecture, practical decisions, and room to grow as your business evolves.'}].map(({n,icon:Icon,title,text})=><article className="why-card" data-reveal key={n}><div><Icon size={29} strokeWidth={1.3}/><span>{n}</span></div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
<section id="work" className="section work-section"><div className="container"><div className="section-heading"><div><span className="eyebrow"><span className="status-dot"/>WORK THAT MOVES BUSINESS</span><h2><AnimatedText text="Ideas into impact."/></h2></div><Link href="/case-studies" className="text-link">View all case studies <ArrowUpRight size={18}/></Link></div><OutcomeCarousel/></div></section>
<section id="process" className="section process-section"><div className="container"><div className="section-heading"><div><span className="eyebrow"><span className="status-dot"/>THE WAY FORWARD</span><h2><AnimatedText text="A clear process."/><br/><span className="muted-title"><AnimatedText text="Extraordinary possibilities."/></span></h2></div><p className="section-note">Every great outcome starts with a shared understanding of where we’re going.</p></div><ProcessExperience/></div></section>
<BigMarquee/><PossibilityPanels/>
<section className="section industries-section"><div className="container"><div className="section-heading"><div><span className="eyebrow"><span className="status-dot"/>BUILT FOR YOUR WORLD</span><h2><AnimatedText text="Different industries."/><br/><span className="muted-title"><AnimatedText text="One drive to move forward."/></span></h2></div><p className="section-note">Technology shaped around the way your industry works, and the people it serves.</p></div><IndustryCards/></div></section>
<section className="section workplace-section"><div className="container workplace-grid"><div className="workplace-copy" data-reveal><span className="eyebrow"><span className="status-dot"/>YOUR WORKPLACE, REIMAGINED</span><h2><AnimatedText text="Less friction."/><br/><span className="muted-title"><AnimatedText text="More flow."/></span></h2><p>Bring the best of Microsoft 365 into the way your team works. Connected tools, intelligent workflows, and shared knowledge—working together.</p><div className="workplace-capabilities"><span><Check size={16}/>SharePoint & Teams</span><span><Check size={16}/>Power Platform</span><span><Check size={16}/>Copilot & AI</span><span><Check size={16}/>Migration & integration</span></div><Link href="/microsoft-365-services" className="button button-dark">Explore Microsoft 365 <ArrowUpRight size={18}/></Link></div><div className="workplace-visual image-reveal"><img src="/images/service-m365.webp" alt="Connected Microsoft 365 workplace technology illustration" loading="lazy"/><div className="workplace-glass-card"><GridMark/><div><strong>One connected workplace.</strong><span>Built around your people.</span></div><ArrowUpRight size={23}/></div><span className="workplace-caption">COLLABORATION, WITHOUT THE COMPLEXITY.</span></div></div></section>
<GlassFlowFeature/><VisualRibbon/>
<section className="section people-section"><div className="container people-grid"><div className="people-image image-reveal"><img src="/images/workspace.webp" alt="Conceptual modern design and engineering studio" loading="lazy"/><div className="people-image-caption"><span className="status-dot"/>A SHARED SPACE FOR BIG IDEAS</div></div><div className="people-copy" data-reveal><span className="eyebrow"><span className="status-dot"/>HUMAN AT HEART</span><h2><AnimatedText text="Great technology."/><br/><span className="muted-title"><AnimatedText text="Even better together."/></span></h2><p>Curious minds. Different perspectives. One shared ambition to build things that make a difference. Meet the thinking behind Elevix.</p><div className="people-links"><Link href="/overview" className="text-link">Our story <ArrowUpRight size={18}/></Link><Link href="/careers" className="text-link">Build your future with us <ArrowUpRight size={18}/></Link></div></div></div></section>
<section id="insights" className="section insights-section"><div className="container"><div className="section-heading"><div><span className="eyebrow"><span className="status-dot"/>THE ELEVIX PERSPECTIVE</span><h2><AnimatedText text="Stay curious."/><br/><span className="muted-title"><AnimatedText text="Stay ahead."/></span></h2></div><Link href="/blogs" className="text-link">All insights <ArrowUpRight size={18}/></Link></div><InsightsCarousel posts={posts}/></div></section>
<PartnershipCards/>
<section className="section faq-section"><div className="container faq-home-grid"><div data-reveal><span className="eyebrow"><span className="status-dot"/>A LITTLE MORE CLARITY</span><h2><AnimatedText text="Good questions."/><br/><span className="muted-title"><AnimatedText text="Thoughtful answers."/></span></h2><p>Everything starts with a conversation.</p><Link href="/faq" className="text-link">Explore all FAQs <ArrowUpRight size={18}/></Link></div><HomeFaq/></div></section><CallToAction/></main>}
function GridMark(){return <span className="microsoft-mark" aria-hidden="true"><i/><i/><i/><i/></span>}
